### ISSUE TITLE
demo, functionalities selection

### ISSUE THREAD

**Issue by EricDS-INFO** [fullstacktf/myment-front#26]
We have to meet (digitaly or materialy ) in order to discuss which of all the functionalities are we gonna include for the demo for the presentation day

**Comment by EricDS-INFO** [comment]
I suggest to keep with :
- random itinerary or  custom itinerary (only one of them)
- user profile (obviously) (with the option to upload an idea)
- main page (hub)
- front page (with option to acces directly to the generator and the direct view of the brand)

for the tryharders: 
- a simple moment galery

(the rest of the functionalities and ideas must be postponed bc of the time we have to end with the project
)

**Comment by armandodecanha** [comment]
And the 2 minutes thing? It's 2 minutes per person or what?

**Comment by EricDS-INFO** [comment]
I am not talking about the presentation, i want to select what are we going to develop in order to show just that the day of presentation

**Comment by EricDS-INFO** [comment]
so i sugested to pick only one itinerary functionality and postpone the galery, the ranking and many other things.

**Comment by pabloderivia** [comment]
I suggest to detail each and every components, clasified by views. For example: 
**Main page**
  - NewsHeader
      - Logo
      - NewsBar

  - InstantSideBar (links to 'generate short', 'add myment (photo)', 'share cool and trendy status' and the 4th option
       - 4X SingleLinkMenu -> props: _name_ (text would be showed) and _path_ (view/route which 
       will be displayed

 - Ranking (secondary/visualOnly. Not a priority)
 - 3X Buttons (gen, add and exp, although quite more funcionalities will be added to this component)

**Comment by ArcaDelDelirio** [comment]
if we takes that classification system we 'll break the rules of atomic development process

**Comment by ArcaDelDelirio** [comment]
I suggest mocks the views and identify the components to develop

**Comment by EricDS-INFO** [comment]
But Oscar, we are not using React :eyes:

**Comment by ArcaDelDelirio** [comment]
with Vuex yes we will use react

**Comment by pabloderivia** [comment]
> if we takes that classification system we 'll break the rules of atomic development process

I just suggest that classification to see each and every component we would need, just like a control system. Ofc, we will code the same component two times, but add some additional funcionalities

**Comment by ArcaDelDelirio** [comment]
Ok ! Sorry i was missunderstanding you. Yes, like clasiffication system only is good, we are in the same point, but different perspective. 👾 
You can use this system as doc clasification system. If @EricDS-INFO  and @pabloderivia feel like bosses can you pass the description of components docs to:
>www.docz.site
>Docz
>It has never been so easy to document your things
Only for document the components and their uses.

**Comment by pabloderivia** [comment]
yes, we are working on it! It will be finished soon 💪
